; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;-----------------------------------------------------------------------------
; The project was successfully compiled with version 55.03.38-1 of the
; pioarduino-espressif32 platform released on May 6, 2026.
; This was tested using the pioarduinoIDE extension (v1.4.0) which is a fork
; of the PlatformioIDE extension. It is available in the Visual Studio Code
; marketplace and in the VSCodium marketplace. The sketch was tested
; using VSCodium (Version 1.116.02821).                           May 10, 2026
;-----------------------------------------------------------------------------

[platformio]
;default_envs = seeed_xiao_esp32c3
;default_envs = seeed_xiao_esp32s3
default_envs = nologo_esp32c3_super_mini
;default_envs = lolin32_lite

[extra]
bflags =                    ; common build flags
  -DCORE_DEBUG_LEVEL=0      ; options: 5 verbose, 4 debug, 3 info, 2 error, 1 critical, 0 none (default)
  -DCOMPILE_TIME=$UNIX_TIME ; Unix (epoch) time stamp of host at compile time
  -DSYNC_POLL_TIME=10000    ; milliseconds (ms) = 10 seconds, time between attempts for the first GPS time synchronization
  -DGPS_POLL_TIME=3600000   ; milliseconds (ms) = 1 hour, time between attempts for following GPS time synchronizations
  -DSAVE_CLOCK_TIME=7200000 ; milliseconds (ms) = 2 hours, time between attempts to save ESP RTC time to NVS and hardware RTC
  -DGPS_WARNING_TIME=300000 ; milliseconds (ms) = 5 minutes, time interval between NO GPS FOUND messages
  -DCONNECT_TIMEOUT=60000   ; milliseconds (ms) = 1 minute, time allowed to connect to the network
  -DGPS_BAUD=9600           ; Baud of GPS module (default 9600)
  -DENABLE_DBG=1            ; debug to serial monitor: 0 = no, 1 = yes
  -DSHOW_NMEA=0             ; dump NMEA message: 0 = no, 1 = GNRMC messages, 2 = all messages
  '-DLOCAL_TIME_ZONE="AST4ADT,M3.2.0,M11.1.0"'
    ;
    ; The Atlantic Time Zone or Atlantic Standard Time (AST) is four hours behind the
    ; Greenwich Mean Time (UTC/GMT -4). Atlantic Daylight Time (ADT) is three hours
    ; behind the Greenwich Mean Time (UTC/GMT -3).
    ; The change from AST to ADT is at 02:00 AST to 03:00 ADT on the second Sunday in March.
    ; The change from ADT to AST is at 02:00 ADT to 01:00 AST on the first Sunday in November.
    ; So that would be time_zone = "AST4ADT,M3.2.0/2,M11.1.0/2" but
    ; https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv
    ; has America/Halifax = AST4ADT,M3.2.0,M11.1.0
    ;
    ; About string macros: https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html#stringification

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
lib_deps =
  mikalhart/TinyGPSPlus@^1.0.3
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.2.0
  https://github.com/AbdulKus/72x40oled_lib.git
  makuna/RTC@^2.4.1


[env:seeed_xiao_esp32c3]
board = seeed_xiao_esp32c3
monitor_speed = 460800
build_flags =
  ${extra.bflags}
  -DHDW_SERIAL_INTF=Serial0
  -DHAS_OLED=0
  -DHAS_DS3231=0

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3
monitor_speed = 460800
build_flags =
  ${extra.bflags}
  -DHDW_SERIAL_INTF=Serial0
  -DHAS_OLED=0
  -DHAS_DS3231=0
  
[env:nologo_esp32c3_super_mini]
board = nologo_esp32c3_super_mini
monitor_speed = 460800         
build_flags =
  ${extra.bflags}
  -DTX_POWER=WIFI_POWER_11dBm
  -DHDW_SERIAL_INTF=Serial0
  -DHAS_OLED=0
  -DHAS_DS3231=0

[env:lolin32_lite]
board =lolin32_lite
monitor_speed = 115200         
build_flags =
  ${extra.bflags}
  -DSERIAL_BAUD=115200
  -DHDW_SERIAL_INTF=Serial1
  -DUART_RX_PIN=16
  -DHAS_OLED=0
  -DHAS_DS3231=0
